# Generated by Django 3.2.7 on 2022-06-08 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('speciality', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('member', 'Member'), ('editor', 'Editor')], default='member', max_length=20)),
                ('work_details', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=1000)),
                ('picture', models.ImageField(upload_to='images')),
            ],
        ),
    ]
