# Generated by Django 3.2.7 on 2022-06-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_join_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='pdfs')),
            ],
        ),
    ]
