# Generated by Django 3.2.7 on 2022-06-25 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_publication_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication_pdf',
            name='file',
            field=models.FileField(upload_to='pdfs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
