# Generated by Django 4.0.6 on 2022-08-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_join_us_area_intrest_professional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_us',
            name='certificate_no',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
