# Generated by Django 4.0.6 on 2022-08-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_join_us_certificate_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join_us',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
