# Generated by Django 3.2.7 on 2022-07-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doante_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=800)),
                ('pan_no', models.CharField(max_length=20)),
                ('transaction_detail', models.CharField(max_length=800)),
                ('approve', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
