# Generated by Django 3.2.7 on 2022-07-04 16:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20220702_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate_receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=10)),
                ('received_date', models.DateField(verbose_name=django.utils.timezone.now)),
                ('donate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donate_receipt', to='root.doante_us')),
            ],
        ),
    ]
