# Generated by Django 4.0.6 on 2022-07-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_donate_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='m_number',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='donate_receipt',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
