# Generated by Django 4.0.6 on 2022-07-17 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_doante_us_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='doante_us',
            name='date_ofdonation',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='doante_us',
            name='donation_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='doante_us',
            name='entered_amount',
            field=models.IntegerField(null=True),
        ),
    ]
