# Generated by Django 4.0.6 on 2022-08-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_doante_us_date_ofdonation_doante_us_donation_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doante_us',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
